;0表示客户端模式，1表示自动化模式，2表示SDK模式
workmode=1
calibmode=1
;软件开关数据传输给SDK配置 1开启 0关闭 sceneData控制全部数据 increasemesh单独控制增量网格数据
sceneData=0
increasemesh=0
; 是否显示（记录）收到的当前片RT
showCurrentRT=0

serviceFile=FreeScan/FreeScan.exe

[freescan_save]
;保存当前标志点
save_CurrentMarkers=0 
;保存整体标志点
save_WholeMarkers=0 
;保存当前点云
save_CurrentCloud=0
;保存整体点云
save_WholeCloud=0
;保存RT
save_rt=0
;暂停扫描后保存整体数据，封装后保存整体数据
save_mesh_stl=0 
;保存增量数据
save_increase_stl=0
;保存文件夹
save_path=save_asc_stl